version: 2
updates:
  - package-ecosystem: composer
    directory: "/tools/phpstan"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 2
  - package-ecosystem: composer
    directory: "/tools/cs-fixer"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 2
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
