--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/VanillaEntityAI
build-by-default: true
projects:
  VanillaEntityAI:
    path: ""
    icon: "icon.png"
    lint: false
    excludeDirs:
      - tests
      - .github
      - build
      - tools
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
    libs:
      - src: jasonwynn10/pathfinding/Pathfinding
        version: ^1.0.0
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
...
