--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/VanillaEntityAI
build-by-default: true
projects:
  VanillaEntityAI:
    path: ""
    icon: "icon.png"
    lint: false
    excludeDirs:
      - tests
      - .github
      - build
      - phpstan
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
...
