blank_issues_enabled: false
contact_links:
  - name: Help & support on Discord
    url: https://discord.gg/R7kdetE
    about: We don't accept support requests on the issue tracker. Please try asking on Discord instead.
  - name: Help & support on forums
    url: https://forums.pmmp.io
    about: We don't accept support requests on the issue tracker. Please try asking on forums instead.
