<?php
declare(strict_types=1);
namespace jasonwynn10\VanillaEntityAI\entity\hostile;

use pocketmine\level\Position;

class CaveSpider extends Spider implements CustomMonster{
	public const NETWORK_ID = self::CAVE_SPIDER;

	public $width = 1.438;
	public $height = 0.547;

	public function initEntity() : void {
		parent::initEntity(); // TODO: Change the autogenerated stub
	}

	/**
	 * @param int $tickDiff
	 *
	 * @return bool
	 */
	public function entityBaseTick(int $tickDiff = 1) : bool {
		return parent::entityBaseTick($tickDiff); // TODO: Change the autogenerated stub
	}

	/**
	 * @return array
	 */
	public function getDrops() : array {
		return parent::getDrops(); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
	public function getName() : string {
		return "Cave Spider";
	}

	public function getTarget() : ?Position {
		// TODO: Implement getTarget() method.
	}
}