<?php
declare(strict_types=1);
namespace jasonwynn10\VanillaEntityAI\entity\hostile;

use jasonwynn10\VanillaEntityAI\entity\Linkable;
use pocketmine\entity\Creature;
use pocketmine\entity\Entity;
use pocketmine\entity\Explosive;
use pocketmine\entity\Living;
use pocketmine\entity\Monster;
use pocketmine\event\entity\EntityDamageByEntityEvent;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\event\entity\ExplosionPrimeEvent;
use pocketmine\level\Explosion;
use pocketmine\level\Position;
use pocketmine\math\AxisAlignedBB;
use pocketmine\nbt\tag\CompoundTag;
use jasonwynn10\VanillaEntityAI\entity\passiveaggressive\Player;

class Creeper extends Monster implements CustomMonster, Explosive {
	public const NETWORK_ID = self::CREEPER;
	public $width = 0.7;
	public $height = 1.7;
	/** @var Position|null */
	protected $target;
	protected $bombTime = 30;
	protected $speed = 0.9;
	protected $stepHeight = 1.0;
	protected $charged = false;
	private $startExplosion = false;
	private $ignited = false;

	public function initEntity(): void {
		parent::initEntity(); // TODO: Change the autogenerated stub
	}

	public function onUpdate(int $currentTick): bool {
		if($this->closed) {
			return false;
		}
		$tickDiff = $currentTick - $this->lastUpdate;
		if($this->target !== null) {
			$x = $this->target->x - $this->x;
			$y = $this->target->y - $this->y;
			$z = $this->target->z - $this->z;
			$diff = abs($x) + abs($z);
			if($this->target instanceof Entity or $this->ignited) {
				if($this->target->distance($this) <= 3) {
					$this->startExplosion = true;
				}
				if($this->startExplosion or $this->ignited) {
					if($this->ignited or ((($this->target instanceof Player and $this->target->isSurvival()) or $this->target instanceof Creature) and $this->target->distance($this) <= 7 and $this->hasLineOfSight($this->target))) {
						$this->setGenericFlag(self::DATA_FLAG_IGNITED, true);
						$this->bombTime -= $tickDiff;
						if($this->bombTime <= 0 and $this->isAlive()) {
							$this->explode();
							return false;
						}
					}else {
						$this->bombTime += $tickDiff;
						$this->setGenericFlag(self::DATA_FLAG_IGNITED, false);
						if($this->bombTime >= 30) {
							$this->bombTime = 30;
							$this->startExplosion = false;
						}
					}
				}else {
					$this->bombTime = 30;
				}
			}
			if($diff > 0) {
				if(!$this->startExplosion) { // do not move while exploding
					$this->motion->x = $this->speed * 0.15 * ($x / $diff);
					$this->motion->z = $this->speed * 0.15 * ($z / $diff);
				}
				$this->yaw = rad2deg(-atan2($x / $diff, $z / $diff));
			}
			$this->pitch = $y == 0 ? 0 : rad2deg(-atan2($y, sqrt($x * $x + $z * $z)));
		}else {
			// TODO: wandering AI
		}
		return parent::onUpdate($currentTick);
	}

	public function ignite() : void {
		$this->ignited = true;
		$this->scheduleUpdate();
	}

	public function explode() {
		$this->server->getPluginManager()->callEvent($ev = new ExplosionPrimeEvent($this, $this->charged ? 6 : 3));
		if(!$ev->isCancelled()) {
			$explosion = new Explosion($this, $ev->getForce(), $this);
			$ev->setBlockBreaking(true); // TODO: mob griefing config
			if($ev->isBlockBreaking()) {
				$explosion->explodeA();
			}
			$explosion->explodeB();
		}
		$this->flagForDespawn();
	}

	public function getSpeed(): float {
		return $this->speed;
	}

	/**
	 * @param int $tickDiff
	 *
	 * @return bool
	 */
	public function entityBaseTick(int $tickDiff = 1): bool {
		if(isset($this->target)) {
			$this->speed = 1.2;
			if($this->distance($this->target) > 16) {
				$this->target = null;
			}
		}else {
			$this->speed = 0.9;
			foreach($this->hasSpawned as $player) {
				if($player->isSurvival() and $this->distance($player) <= 16 and $this->hasLineOfSight($player)) {
					$this->target = $player;
				}
			}
		}
		/** @var Player $player */
		foreach($this->hasSpawned as $player) {
			if($player->canInteract($this, $player->isCreative() ? 13 : 7) and $player->getLookingAt() === $this) {
				$player->getDataPropertyManager()->setString(self::DATA_INTERACTIVE_TAG, "Ignite");
			}
		}
		return parent::entityBaseTick($tickDiff);
	}

	/**
	 * Entity gets attacked by another entity / explosion or something similar
	 *
	 * @param EntityDamageEvent $source the damage event
	 */
	public function attack(EntityDamageEvent $source): void {
		parent::attack($source);
		if(!$this->target instanceof Player) {
			if($source instanceof EntityDamageByEntityEvent) {
				$damager = $source->getDamager();
				if($damager instanceof Player and $damager->isSurvival() and $this->distance($damager) <= 16 and abs($this->y - $damager->y) <= 4) {
					$this->target = $damager;
				}elseif(!$damager instanceof Player and $this->distance($damager) <= 16 and abs($this->y - $damager->y) <= 4) {
					$this->target = $damager;
				}
			}
		}
	}

	/**
	 * @return array
	 */
	public function getDrops(): array {
		return parent::getDrops(); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
	public function getName(): string {
		return "Creeper";
	}

	public function getTarget(): ?Position {
		return $this->target;
	}

	/**
	 * @param Position $spawnPos
	 * @param CompoundTag|null $spawnData
	 *
	 * @return null|Living
	 */
	public static function spawnMob(Position $spawnPos, ?CompoundTag $spawnData = null) : ?Living {
		$width = 0.7;
		$height = 1.7;
		$boundingBox = new AxisAlignedBB(0, 0, 0, 0, 0, 0);
		$halfWidth = $width / 2;
		$boundingBox->setBounds($spawnPos->x - $halfWidth, $spawnPos->y, $spawnPos->z - $halfWidth, $spawnPos->x + $halfWidth, $spawnPos->y + $height, $spawnPos->z + $halfWidth);
		// TODO: work on logic here more
		if(!$spawnPos->isValid() or !$spawnPos->level->getBlock($spawnPos->subtract(0, 1), true, false)->isSolid() or $spawnPos->level->getFullLight($spawnPos) > 7) {
			return null;
		}
		$nbt = self::createBaseNBT($spawnPos);
		if(isset($spawnData)) {
			$nbt = $spawnData->merge($nbt);
			$nbt->setInt("id", self::NETWORK_ID);
		}
		/** @var self $entity */
		$entity = self::createEntity("Creeper", $spawnPos->level, $nbt);
		return $entity;
	}

	/**
	 * @return Linkable|null
	 */
	public function getLink() : ?Linkable {
		// TODO: Implement getLink() method.
	}

	/**
	 * @param Linkable $entity
	 */
	public function setLink(Linkable $entity) {
		// TODO: Implement setLink() method.
	}

	/**
	 * @return bool
	 */
	public function isCharged() : bool {
		return $this->charged;
	}

	/**
	 * @param bool $charged
	 *
	 * @return Creeper
	 */
	public function setCharged(bool $charged = true) : self {
		$this->charged = $charged;
		$this->setGenericFlag(self::DATA_FLAG_CHARGED, $charged);
		return $this;
	}

	/**
	 * @param float $speed
	 *
	 * @return Creeper
	 */
	public function setSpeed(float $speed) {
		// TODO: Implement setSpeed() method.
	}
}