<?php
declare(strict_types=1);
namespace jasonwynn10\VanillaEntityAI\entity\passive;

use pocketmine\entity\Creature;

class Bat extends Creature {
	public function initEntity() {
		parent::initEntity(); // TODO: Change the autogenerated stub
	}

	public function entityBaseTick(int $tickDiff = 1) : bool {
		return parent::entityBaseTick($tickDiff); // TODO: Change the autogenerated stub
	}

	public function getDrops() : array {
		return parent::getDrops(); // TODO: Change the autogenerated stub
	}

	public function getName() : string {
		return "Bat";
	}
}