<?php
declare(strict_types=1);
namespace jasonwynn10\VanillaEntityAI\entity\passive;

use jasonwynn10\VanillaEntityAI\entity\passiveaggressive\Player;
use pocketmine\entity\Entity;
use pocketmine\entity\EntityIds;
use pocketmine\item\Bowl;
use pocketmine\item\Item;
use pocketmine\item\ItemFactory;
use pocketmine\item\Shears;
use pocketmine\network\mcpe\protocol\LevelSoundEventPacket;

class Mooshroom extends Cow {
	public const NETWORK_ID = self::MOOSHROOM;
	public $width = 1.781;
	public $height = 1.875;


	public function initEntity() : void {
		parent::initEntity();

	}

	/**
	 * @param int $tickDiff
	 *
	 * @return bool
	 */
	public function entityBaseTick(int $tickDiff = 1) : bool {
		return parent::entityBaseTick($tickDiff); // TODO: Change the autogenerated stub
		// TODO: Sheep follow players holding wheat within 8 blocks
	}

	/**
	 * @return string
	 */
	public function getName() : string {
		return "Mooshroom";
	}

	/**
	 * @param Entity $entity
	 */
	public function onCollideWithEntity(Entity $entity) : void {
		// TODO: Red mooshrooms convert to brown mooshrooms, and brown convert to red, when they are struck by lightning.
	}

	public function onPlayerLook(Player $player) : void {
		$hand = $player->getInventory()->getItemInHand();
		if(!$this->isBaby() and $hand instanceof Shears) {
			$this->getDataPropertyManager()->setString(Entity::DATA_INTERACTIVE_TAG, "Shear");
		}
		if(!$this->isBaby() and $hand instanceof Bowl) {
			$this->getDataPropertyManager()->setString(Entity::DATA_INTERACTIVE_TAG, "Mushroom Stew");
		}
		parent::onPlayerLook($player);
	}

	public function onPlayerInteract(Player $player) : void {
		$hand = $player->getInventory()->getItemInHand();
		if(!$this->isBaby() and $hand instanceof Shears) {
			$this->shear();
			$hand->applyDamage(1);
			$player->getInventory()->setItemInHand($hand);
			$this->level->broadcastLevelSoundEvent($player, LevelSoundEventPacket::SOUND_SHEAR, 0, EntityIds::PLAYER);
		}
		if(!$this->isBaby() and $hand instanceof Bowl) {
			$hand = ItemFactory::get(Item::MUSHROOM_STEW);
			$player->getInventory()->setItemInHand($hand);
		}
		parent::onPlayerInteract($player);
	}

	public function shear() : self {
		$this->level->dropItem($this, ItemFactory::get(Item::RED_MUSHROOM, 0, 5));
		$cow = Cow::createEntity("Cow", $this->level, Cow::createBaseNBT($this, $this->motion, $this->yaw, $this->pitch));
		if($cow !== null) {
			$this->level->addEntity($cow);
			$this->flagForDespawn();
			$cow->spawnToAll();
		}
		return $this;
	}
}