<?php
declare(strict_types=1);
namespace jasonwynn10\VanillaEntityAI\entity\passive;

class Villager extends \pocketmine\entity\Villager {
	public function initEntity() {
		parent::initEntity(); // TODO: Change the autogenerated stub
	}

	public function onUpdate(int $currentTick) : bool {
		return parent::onUpdate($currentTick); // TODO: Change the autogenerated stub
	}
}