<?php
declare(strict_types=1);
namespace jasonwynn10\VanillaEntityAI\entity;

use pocketmine\entity\Ageable;
use pocketmine\event\entity\EntityDamageEvent;

abstract class AnimalBase extends CreatureBase implements Ageable {
	use AgeableTrait;
	/** @var int $panicTime */
	protected $panicTime = 100;

	/**
	 * @param EntityDamageEvent $source
	 */
	public function attack(EntityDamageEvent $source) : void {
		$this->setPanic();
		parent::attack($source);
	}
	public function entityBaseTick(int $tickDiff = 1) : bool {
		if($this->panicTime -= $tickDiff <= 0 )
			$this->setPanic(false);
		return parent::entityBaseTick($tickDiff); // TODO: Change the autogenerated stub
	}

	public function setPanic(bool $panic = true) : void {
		$this->setSprinting($panic);
		if($panic)
			$this->moveTime = 0;
	}
}