<?php
declare(strict_types=1);
namespace jasonwynn10\VanillaEntityAI\entity\neutral;

use jasonwynn10\VanillaEntityAI\entity\CreatureBase;
use jasonwynn10\VanillaEntityAI\entity\Linkable;
use pocketmine\entity\Entity;

class Minecart extends Entity implements Linkable {
	/** @var CreatureBase $link */
	private $link;

	public function initEntity() : void {
		parent::initEntity(); // TODO: Change the autogenerated stub
	}

	/**
	 * @param int $tickDiff
	 *
	 * @return bool
	 */
	public function entityBaseTick(int $tickDiff = 1) : bool {
		return parent::entityBaseTick($tickDiff); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
	public function getName() : string {
		return "Minecart";
	}

	/**
	 * @return CreatureBase|null
	 */
	public function getLink() : ?Linkable {
		return $this->link;
	}

	/**
	 * @param Linkable $entity
	 */
	public function setLink(Linkable $entity) {
		$this->link = $entity;
	}
}